package:
  name: goic
  version: "1.2.3"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - gensim
    - nltk

  run:
    - python

test:
  # Python imports
  imports:
    - goic

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - goic-params --help
    - goic-train --help
    - goic-predict --help

  requires:
    # Put any additional test requirements here.  For example
    - numpy
    - scipy
    - scikit-learn
    - gensim
    - nltk
about:
  home: https://github.com/ingeotec/goic
  summary: "Optimized Gabor-based image classifiers."
  license: Apache
